<a href="https://colab.research.google.com/github/wayneotemah/Learing-TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamentals concepts of tensors using TensorFlow

more specifically:
introduction to tensers

*   getting information from tensers
*   manipulating tensers
*   using @tf.function (a way to speed up regualar py functions)
*   using GPUs with tensorflow
* Exercises to try for myself

# Intrduction to tensers

In [ ]:
# import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim -> stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check vector dimentions
vector.ndim

1

In [ ]:
# create a matrix ( more than one dimension)

matrix = tf.constant([[10,10,19],
                      [12,6,3]])

matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 19],
       [12,  6,  3]], dtype=int32)>

In [ ]:
# matrix number of dimensions
matrix.ndim

2

In [ ]:
# create tensor with our own datatype

another_matrix = tf.constant([[10.,10.],
                              [3.,2.,],
                             [8.,9.]],dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# check  another matix's
another_matrix.ndim

2

In [ ]:
#  increasing number of dimension
tensor = tf.constant([[[1,2,3],
                        [5,6,7]],
                        [[9,8,7],
                         [7,6,5]]])

tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 7]],

       [[9, 8, 7],
        [7, 6, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# waht we have learned so far
 * scalar: a single dimension
 * venctor: a number with direction (wind speed and direction)
 * matrix: 2 dimensioins of numbers
 * tensor: an n dimensional array of numbers