<a href="https://colab.research.google.com/github/wayneotemah/Learing-TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamentals concepts of tensors using TensorFlow

more specifically:
introduction to tensers

*   getting information from tensers
*   manipulating tensers
*   using @tf.function (a way to speed up regualar py functions)
*   using GPUs with tensorflow
* Exercises to try for myself

# Intrduction to tensers

In [ ]:
# import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim -> stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check vector dimentions
vector.ndim

1

In [ ]:
# create a matrix ( more than one dimension)

matrix = tf.constant([[10,10,19],
                      [12,6,3]])

matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 19],
       [12,  6,  3]], dtype=int32)>

In [ ]:
# matrix number of dimensions
matrix.ndim

2

In [ ]:
# create tensor with our own datatype

another_matrix = tf.constant([[10.,10.],
                              [3.,2.,],
                             [8.,9.]],dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# check  another matix's
another_matrix.ndim

2

In [ ]:
#  increasing number of dimension
tensor = tf.constant([[[1,2,3],
                        [5,6,7]],
                        [[9,8,7],
                         [7,6,5]]])

tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 7]],

       [[9, 8, 7],
        [7, 6, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# what we have learned so far
 * scalar: a single dimension
 * venctor: a number with direction (wind speed and direction)
 * matrix: 2 dimensioins of numbers
 * tensor: an n dimensional array of numbers

# Creating tensors with tf.variable

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets try chabginging one of the elements in the changeable tensor
# use the .assign(x) to change the value
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# changing value in the unchangeable tensor
# tf.constant can not be changed one set


# unchangeable_tensor[0].assign(7)

# creating random tensors



These are tensors of some abitrary size containing rundom numbers. 

In [ ]:
#  creating two random but same tensors
# using .random.unifrom -> Outputs random values from a uniform distribution.

random1 = tf.random.uniform(shape=[3,5],
                                  maxval=5,
                                  dtype = tf.int32)
random1

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[4, 4, 3, 4, 1],
       [3, 1, 3, 1, 4],
       [4, 1, 0, 0, 4]], dtype=int32)>

In [ ]:
random2 = tf.random.Generator.from_seed(43)
random2 = random2.normal(shape=(3,5))
random2

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ,  0.09988727, -0.50998646, -0.7535805 ],
       [-0.57166284,  0.1480774 , -0.23362993, -0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ]],
      dtype=float32)>

In [ ]:
random3 = tf.random.Generator.from_seed(43)
random3 = random3.normal(shape = (3,5))

# are they equale, random3 and random2

random2,random3, random2==random3


(<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ,  0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993, -0.3522796 ,  0.40621263],
        [-1.0523509 ,  1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ,  0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993, -0.3522796 ,  0.40621263],
        [-1.0523509 ,  1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=bool, numpy=
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])>)

## Shuffle the oder of elemets in a tenor

In [ ]:
#shuffle a tensor
# the inherent order does not affect learning

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

not_shuffled.ndim
                             

2

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(30)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed = 30)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

# Other ways to make tensors


In [ ]:
tf.ones([10,7]) # create a tensor or all ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,4)) #create a tensor of all zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#turning  nummpy array in to tensorflow tensors

the main diffrenece between tensors and numpy array is that, tensors can be run in a gpu faster than nummpy array. Else they are very similar

In [ ]:
#turning  nummpy array in to tensorflow tensors
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape =(2,3,4))
A.ndim

3

Getting infromatioin from Tensors

* shape
* rank
* axis/dimension
* size 

In [ ]:
#create a rank for tensor

rank_4_tf = tf.ones(shape=(2,2,3,4))
rank_4_tf.ndim, rank_4_tf

(4,
 <tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
 array([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]], dtype=float32)>)

In [ ]:
rank_4_tf[0],rank_4_tf.shape,tf.size(rank_4_tf).numpy(   )

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=float32)>,
 TensorShape([2, 2, 3, 4]),
 48)

In [ ]:
#adding an extradimentions to a tensor
rank_2_tf = tf.constant([[20,1],
                        [4,5]])

rank_2_tf[:,-1].numpy()

array([1, 5], dtype=int32)

In [ ]:
some_list = [1,2,4,5,]
some_list[-1]

5

In [ ]:
# reshaping the tensor with tf.newaxis
rank_3_tf = rank_2_tf[...,tf.newaxis]
rank_3_tf

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[20],
        [ 1]],

       [[ 4],
        [ 5]]], dtype=int32)>

In [ ]:
# reshaping the tensor with 
tf.expand_dims(rank_2_tf,axis = -1) # '-1' means expand from the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[20],
        [ 1]],

       [[ 4],
        [ 5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tf,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[20,  1],
        [ 4,  5]]], dtype=int32)>

# Manipulating tensors (tensor operations)

## basic operations

`+`,`-`,`*`.`/`

In [ ]:
# tensor addition

tensor = tf.constant([[10,7],[3,4]])
tensor+10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# use the tf build in too
tf.subtract(tensor,10)
tf.multiply(tensor,10)
tf.add(tensor,10)
tf.divide(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

# matrix multiplicatipn
### one  of the most used tensor operations

Rules for matrix multiplications:
1. Inner dimensions must match
2. the resulting matrixs has the shape of the inner dimensions 

In [ ]:
X = tf.constant([1,2,5,7,2,1,3,3,3], shape = [3,3])
Y = tf.constant([3,5,6,7,1,8], shape = [3,2])

tf.matmul(X,Y)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
X @ Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
Y_reshaped = tf.reshape(Y,shape = (2,3))
Y , Y_reshaped

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [ ]:
tf.transpose(X) @ X

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[59, 25, 21],
       [25, 17, 21],
       [21, 21, 35]], dtype=int32)>

## Changing the datatype of a tensor

In [ ]:
#  tensor with default datatype (float32)

B = tf.constant([1.1,2.3,4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# change from float32 to float16 
D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.1, 2.3, 4. ], dtype=float16)>

In [ ]:
#change from Int 32 to float 32

E = tf.cast(C,dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

# Aggregating tensors

This means condensing tensors from multiple values down to a smaller amount of values 

In [ ]:
D = tf.constant([-7,-10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of aggregation

1. minimum
2. maximum
3. mean of a tensor
4. sum of a tensor

In [ ]:
Z = tf.constant(np.random.randint(0,100,size = 50))
tf.size(Z),Z.shape,Z.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find the minimum
tf.reduce_min(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_max(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
tf.reduce_sum(Z )

<tf.Tensor: shape=(), dtype=int64, numpy=2574>

In [ ]:
# finding variance 

import tensorflow_probability as tfp
tfp.stats.variance(Z)
# or
tf.math.reduce_variance(tf.cast(Z,dtype = tf.float32 ))


<tf.Tensor: shape=(), dtype=float32, numpy=897.9296>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

# Finding the positional maximum and minimum 

*The positional maximum and minimum of a matrix refers to the indices of the maximum and minimum values in the matrix. These indices represent the row and column position of the maximum and minimum values in the matrix.*

In [ ]:
tf.random.set_seed(43)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
      dtype=float32)>

In [ ]:
#find the positional max index
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [ ]:
# use index of our largest value position to find it value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [ ]:
# Find the max value of F unsing the .reduce_max
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [ ]:
# Check for equality

assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# find the posistional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [ ]:
# use index of our smallest value position to find it value
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0015381575>

# Squeezing a tensor (removing all single dimensioins)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.ndim

5

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim, G_squeezed

(TensorShape([50]),
 1,
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

# One-hot encoding

a process by which categorical data variables are converted into numerical values that can be used by ML algorithms to do a better job in prediction

In [ ]:
#  Create List of indices

some_List = [0,1,2,4]

# one hot encode the list
tf.one_hot(some_list,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# specifiy castom values for one hot encoding
tf.one_hot(some_list,4,on_value="True", off_value = "False")
 

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'True', b'False'],
       [b'False', b'False', b'False', b'False'],
       [b'False', b'False', b'False', b'False']], dtype=object)>

# Access to GPU

In [ ]:
import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Apr 28 16:06:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

IF you have access to  a cuda enabled GPU, tensorflow will automatically use it whenever possible 